### PR TITLE
[doc] Editorial updates to the backup and restore section

### PR DESCRIPTION
**Pull request by asettle**
Editing and cleaning up the language in the backup and restore section.

#### Which issue(s) this PR fixes:

Issue #

#### What this PR does / why we need it:

Edits are always wonderful

#### Special notes for your reviewer:

Note: Clarity on the "blocking way" would be appreciated

### CODE REVIEW

**Review by jillian-maroket — APPROVED** [review]

**Review by innobead — CHANGES_REQUESTED** [review]
LGTM. 

Please also help update active versions (1.4.4) and the upcoming 1.6.0, 1.54 and 1.4.5.

**Comment by innobead** [comment]
> LGTM.
> 
> Please also help update active versions (1.4.4) and the upcoming 1.6.0, 1.54 and 1.4.5.

@jillian-maroket can you just help with this? thanks.

**Comment by innobead** [comment]
@jillian-maroket as I mentioned above, please continue this PR, as @asettle seems not finishing this yet.

**Comment by jillian-maroket** [comment]
@innobead Sorry, your comment was missed. I'm working on some time-sensitive Harvester tasks so I'll revisit this once those are completed.

**Comment by innobead** [comment]
> @innobead Sorry, your comment was missed. I'm working on some time-sensitive Harvester tasks so I'll revisit this once those are completed.

@jillian-maroket find time, so we can wrap up this.

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by derekbit** [comment]
ping @jillian-maroket

**Comment by jillian-maroket** [comment]
I could not work with Alex's branch so I created a [new PR](https://github.com/longhorn/website/pull/939/). The suggested changes were applied *as is* to all active versions.

**Comment by derekbit** [comment]
Already addressed in https://github.com/longhorn/website/pull/939. Thanks for your contribution.

**Pull request closed without merging**
