### PR TITLE
Fixed ingress controller creation step upd

### PR DESCRIPTION
**Pull request by marcobellaccini**
Fixed ingress controller creation step.
See https://github.com/longhorn/website/pull/100

Signed-off-by: Marco Bellaccini <marco.bellaccini[at!]gmail.com>

### CODE REVIEW

**Comment by yasker** [comment]
Hi @marcobellaccini , it seems `marco.bellaccini[at!]gmail.com` cannot be accepted as signed-off..

**Comment by yasker** [comment]
Ping @marcobellaccini ?

**Comment by marcobellaccini** [comment]
Hi,
I'm sorry but I prefer not to have my email address exposed in unmasked form on public websites.

If I sign-off the commit like you're asking me to do (i.e.: with `@` instead of `[at!]`), my email address will end-up being available in unmasked form on GitHub webservers.
This would help spambots in performing email-address harvesting.

Since my contribution is really small, if you require that kind of sign-off, I think you can close this PR and, next time you'll be editing that file, fix that line.

Thank you anyway for your cool software.

Cheers

Marco

**Comment by yasker** [comment]
Hi @marcobellaccini 

I understand your concern. There is a way to solve this and still associate this PR to your account. You can use your GitHub `noreply` email: `24960638+marcobellaccini@users.noreply.github.com` (found it in the DCO bot) as your signed-off email.

You can see more at https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#about-commit-email-addresses

**Comment by marcobellaccini** [comment]
Hi @yasker 
thank you!
I was already using GitHub noreply email for commits, but I didn't know that it was considered valid for sign-off.
I updated the commit with the new sign-off address.

**Comment by yasker** [comment]
Thanks @marcobellaccini . LGTM.

**Pull request merged**
