### PR TITLE
docs(v1.8.0): remove old items from important notes

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue #

Signed-off-by: Derek Su <derek.su@suse.com>

### CODE REVIEW

**Review by innobead — DISMISSED** [review]

**Comment by innobead** [comment]
PR checks failed.

So we decide to deprecate the environment check script in 1.9 instead.

**Comment by derekbit** [comment]
> PR checks failed.
> 
> So we decide to deprecate the environment check script in 1.9 instead.

Yes, there are some external contributions that need to move to CLI as well.

**Comment by derekbit** [comment]
> PR checks failed.

Fixed and ready for review.

**Review by jhkrug — APPROVED** [review]
lgtm

**Pull request merged**
