### PR TITLE
Fixed ingress controller creation step

### PR DESCRIPTION
**Pull request by marcobellaccini**
Added missing "-f" option

### CODE REVIEW

**Comment by yasker** [comment]
@marcobellaccini Thanks for the PR. Can you add a `signed-off` for your commit? See https://github.com/longhorn/website#sign-off-on-all-commits

**Comment by marcobellaccini** [comment]
Ok, if you squash-merge it should be fine.

**Comment by yasker** [comment]
Hi @marcobellaccini , we normally use `rebase` as the way to merge, since it will preserve the commit message and order. Is it possible for you to use `git rebase -i` to squash the commits into one? Thanks.

**Comment by marcobellaccini** [comment]
I have no access to my shell in this moment.
However, given the triviality of the fix, I've just created a new PR: https://github.com/longhorn/website/pull/101
I'm closing this one.

**Pull request closed without merging**
