### PR TITLE
Add setting engine-replica-timeout

### PR DESCRIPTION
**Pull request by derekbit**
[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)

Signed-off-by: Derek Su <derek.su@suse.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@derekbit PR check failed. Please check and fix it.

**Comment by innobead** [comment]
image

It seems we need to update the netlify site.

**Comment by derekbit** [comment]
Looks a build image issue?

**Comment by innobead** [comment]
@yangchiu do you have permission to update the netlify site setting?

**Comment by yangchiu** [comment]
No, I don't have any knowledge or handover document about netlify, and when I tried to log in netlify with github, it redirected to sign up page, and I can't find any connection between longhorn in this created account.

**Comment by innobead** [comment]
> No, I don't have any knowledge or handover document about netlify, and when I tried to log in netlify with github, it redirected to sign up page, and I can't find any connection between longhorn in this created account.

No worries, the fix has been figured out :+1:

**Pull request merged**
