### PR TITLE
Add pod-selector to avoid draining Longhorn webhook

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#3304

### CODE REVIEW

**Review by innobead — COMMENTED** [review]
Do we still need driver deployer? 

BTW, currently the deployments of webhooks and CSI sidecars have replicas with pod anti-affinity, so if users do drain nodes one by one, probably it's not required to skip these pods?

**Comment by PhanLe1010** [comment]
> Do we still need driver deployer?

Good catch. Thank you. Fixed

> BTW, currently the deployments of webhooks and CSI sidecars have replicas with pod anti-affinity, so if users do drain nodes one by one, probably it's not required to skip these pods?

We still have problem in single node cluster

**Comment by innobead** [comment]
If a single node, why need to drain?

**Comment by PhanLe1010** [comment]
> If a single node, why need to drain?

When the user upgrades Kubernetes. Drain to stop the workload first so that we don't crash the instance manager when there is active workload. What do you think?

**Comment by PhanLe1010** [comment]
I am also planning to fix the driver deployer so that it doesn't restart the csi deployment when Kubernetes version change for the next version. What do you think?

**Comment by innobead** [comment]
> I am also planning to fix the driver deployer so that it doesn't restart the csi deployment when Kubernetes version change for the next version. What do you think?

As discussed, we all agree with this change to avoid any unexpected CSI sidecars restart caused by the deployer restart during the upgrade.

In different use cases, the usage of draining can be clarified as follows:

- In a multiple-node cluster, if users drain nodes one by one, specific pod exclusion should not be required because CSI sidecars and webhooks already have replicas and pod anti-affinity placement.
- In a single-node cluster, the drain operation seems not quite meaningful because if users want to upgrade K8s, they should shut down all workarounds instead.

What we cannot control is how users perform the drain operation in parallel, so this is why pod exclusion is still needed in the current practice in the doc until a new mechanism introduced in https://github.com/longhorn/longhorn/issues/3304

**Review by innobead — APPROVED** [review]

**Pull request merged**
