### PR TITLE
KB: add "Troubleshooting: RWX Volume Fails to Be Attached Caused by `Protocol not supported`"

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#6887
Longhorn/longhorn#6857

### CODE REVIEW

**Review by jillian-maroket — COMMENTED** [review]
@derekbit Let me know if the changes work.

**Review by derekbit — COMMENTED** [review]
LGTM. Thank you @jillian-maroket .

**Review by shuo-wu — APPROVED** [review]

**Review by jillian-maroket — APPROVED** [review]
LGTM. Thanks!

**Review by innobead — COMMENTED** [review]
LGTM.

**Pull request merged**
