### PR TITLE
http redirect for docs.longhorn.io

### PR DESCRIPTION
**Pull request by lucperkins**
This is my last idea for getting docs.longhorn.io to work. Fingers crossed!

cc @yasker

### CODE REVIEW

**Comment by yasker** [comment]
Seems still doesn't work... As the last resort, I will ask Rancher Labs infra team to help to host a container for the redirect.

**Comment by lucperkins** [comment]
It’s working for me. Give it some time or switch browsers.

**Comment by yasker** [comment]
Wow, the subpath works for me now! But `docs.longhorn.io` itself still pointed to `longhorn.io`

**Comment by lucperkins** [comment]
You can add an additional redirect for the root.

**Pull request merged**
