### PR TITLE
Add a doc explain the node space usage info

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#1519

### CODE REVIEW

**Comment by yasker** [comment]
The content looks good. The first picture is weird though. You can check it by looking into the preview page.

Screen Shot 2020-07-17 at 9 35 41 AM

**Comment by shuo-wu** [comment]
> The content looks good. The first picture is weird though. You can check it by looking into the preview page.
> 
> Screen Shot 2020-07-17 at 9 35 41 AM

I am not sure which part is weird. But I still updated the picture to present more info.

**Comment by yasker** [comment]
@shuo-wu where is the middle circle?...

**Comment by shuo-wu** [comment]
The picture has been updated.

**Pull request merged**
