### PR TITLE
Update longhorn-manager.md

### PR DESCRIPTION
**Pull request by boknowswiki**
This commit is to add one addition migration failure fix for removing
compitable csi deployment from v0.6.2 or older version to v0.8.1.

https://github.com/longhorn/longhorn/issues/1412

Signed-off-by: Bo Tao <bo.tao@rancher.com>

### CODE REVIEW

**Comment by yasker** [comment]
@boknowswiki Please submit the PR against master instead of staging. Staging is for upcoming v1.0.0 release and it's not necessary to mention this there.

**Comment by catherineluse** [comment]
LGTM

**Comment by boknowswiki** [comment]
A new PR against master branch:

https://github.com/longhorn/website/pull/127

**Comment by yasker** [comment]
Close this in favor of #127

**Pull request closed without merging**
