### PR TITLE
Create 1.3.0 docs

### PR DESCRIPTION
**Pull request by jenting**
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by jenting** [comment]
I've changed the wording on the upgrade from v1.2.x

**Review by innobead — CHANGES_REQUESTED** [review]
@jenting can't see the 1.3.0 in the preview, probably need to update config.toml

**Comment by jenting** [comment]
> @jenting can't see the 1.3.0 in the preview, probably need to update config.toml

Isn't that mean the 1.3.0 doc will be visible and marked at the latest.

**Comment by jenting** [comment]
Probably we could enhance it by adding the latest version on the config.toml to point what the current latest version. So, it will be like
- 1.3.0
- 1.2.2 (latest)
- 1.2.1
- ...

But we have to make sure using the latest URL redirect to the current version.

**Comment by innobead** [comment]
I think this was misunderstood :) You should make this PR to v1.3.0 instead of the master branch. I just forked the branch.

**Comment by jenting** [comment]
> I think this was misunderstood :) You should make this PR to v1.3.0 instead of the master branch. I just forked the branch.

Understood.

**Review by innobead — APPROVED** [review]

**Pull request merged**
