### PR TITLE
spdk: add "known issues" page

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#6126

### CODE REVIEW

**Comment by DamiaSan** [comment]
Online node rebuild not available, and maybe all other functionalities still not implemented, are missing features or can be named as known issues?

**Comment by derekbit** [comment]
> Online node rebuild not available, and maybe all other functionalities still not implemented, are missing features or can be named as known issues?

Good question.
Other functions are listed in the `quick start`, so I just mention `actual size` issue here.

**Review by innobead — COMMENTED** [review]
Right, this could make some confusion internally or externally. 

It seems we hide ths actual size in the detailed page for now, https://github.com/longhorn/longhorn-ui/pull/634/files. Derek also explained the future efforts until GA at https://longhorn.io/docs/1.5.0/spdk/#feature-support, so we are good now. 

Closing, thanks for this draft PR.

**Comment by derekbit** [comment]
Not needed.

**Pull request closed without merging**
