### PR TITLE
Site with docs

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by yasker** [comment]
Looks great at first glance. Thanks @lucperkins !

**Comment by lucperkins** [comment]
@yasker Thanks a lot! Still a fair amount more work to do but I do think it's going in a good direction. I'm going to work on documentation restructuring a bit this week and come back to the site next week.

**Comment by lucperkins** [comment]
@yasker Okay, this is ready for review. The docs still need some work but I think that this successfully moves the existing content into the new interface.

**Comment by yasker** [comment]
It looks great! Thanks @lucperkins !

**Comment by yasker** [comment]
One more thing, can we get an example of a hierarchy style index in the docs?

For example:
```
Getting Started
|- Helm
|- Customized Default Settings
|- Google Kubernetes Engine
```

**Comment by yasker** [comment]
Wow, this is kind of snippets are real nice! Thanks!

Screen Shot 2019-12-06 at 2 44 26 PM

**Pull request merged**
