### PR TITLE
Re-add missing diagram to architecture doc

### PR DESCRIPTION
**Pull request by catherineluse**

### CODE REVIEW

**Comment by yasker** [comment]
Is it possible to replace `Docker` with `Kubernetes` in the diagram?

**Comment by catherineluse** [comment]
Lauren said she doesn't have the source file, but she said she would redraw it and change Docker volume to Kubernetes volume.

**Comment by catherineluse** [comment]
I have added Lauren's updated diagram to the architecture page and to Longhorn.io

**Comment by yasker** [comment]
Sorry, I just realized I missed one thing. the rightmost engine is pointing to two replicas on the same node, so does the left-most engine

**Comment by catherineluse** [comment]
I updated it with Lauren's most recent version

**Comment by yasker** [comment]
LGTM. Need to resolve conflict.

**Comment by catherineluse** [comment]
it's fixed now

**Pull request merged**
