### PR TITLE
Add `Important Notes` page

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#2964

### CODE REVIEW

**Comment by PhanLe1010** [comment]
I am not sure why the page `important notes` and the page `uninstallation` are on the same level. Do you have any idea @jenting ?
Screen Shot 2021-09-02 at 12 28 05 PM

**Comment by c3y1huang** [comment]
> I am not sure why the page `important notes` and the page `uninstallation` are on the same level. Do you have any idea @jenting ?
> Screen Shot 2021-09-02 at 12 28 05 PM

Probably because uninstall and impotant-notes folder both contain only single `_index.md`. I think you could just do `important-note.md` as a single file under deploy instead of a folder.

nit: impotant-notes folder is incorrectly spelled.

**Comment by jenting** [comment]
Hmmm... interested. 

Hugo doc has a description on Leaf Bundle v.s Branch Bundle.
For this case, the important-notes would better use Leaf Bundle (rename `_index.md` to `index.md`).

However, I haven't found a way to change the ordering between Leaf Bundle and Branch Bundle yet.
It means the Leaf Bundle would be in front of the Branch Bundle in my testing.

**Comment by PhanLe1010** [comment]
Thanks @jenting

**Review by jenting — APPROVED** [review]

**Review by c3y1huang — APPROVED** [review]

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@PhanLe1010 https://github.com/longhorn/website/pull/374

**Pull request merged**
