### PR TITLE
Adding Knowledge Base page, including content example

### PR DESCRIPTION
**Pull request by hackabletype**
As per issue https://github.com/longhorn/website/issues/197, adding a Knowledge Base page based on the existing architecture of the Blog pages.

Open questions:
- [ ] How do these new pages/sections get added to the Algolia search
- [x] Should this be merged into longhorn/website master branch, or the v1.1.0 branch
- [x] Is there a better content example

### CODE REVIEW

**Comment by zacharysarah** [comment]
Deploy preview: https://deploy-preview-198--longhornio.netlify.app/kb/

**Comment by celestehorgan** [comment]
Comments and questions:

1) If you intend for a page to use the same base layouts as defined in `/layouts/_default`, you don't need to copy them into their own subdirectory, i.e. `/layouts/kb`. Hugo uses a fallback model for layouts, so if it doesn't find any layout files in `/layouts/kb`, it automatically falls back to `/layouts/_default`. 

Follow up question #1: Is the intent to customize the layout of this page?

2) Page structure: is each question going to have its own page, or be a list on _index.md?

3) Re: content examples – this is a knowledge base, I think you can assume each content node is going to be a question-answer pair.

4) Algolia search – this is done via whomever has the login for Algolia for this site, which is not me.

5) Branches: this is up to the maintainers of this project, so please @-mention one for review.


----


Ping me when you've gotten a little further with this :)

**Comment by hackabletype** [comment]
@celestehorgan makes a good suggestion, especially since I don't think I can add reviewers using the UI.

@yasker, could you take a look at this PR (and the couple of questions I've got)?

**Comment by hackabletype** [comment]
@celestehorgan:
> Follow up question #1: Is the intent to customize the layout of this page?

No, my understanding is that I should be like the existing blog pages.

**Comment by hackabletype** [comment]
I reverted the commit where I removed the layouts/kb files for two reasons:
1. The change broke the deploy-preview
2. I think we actually do need them. Without them the Knowledge Base pages don't get formatted as the Blog pages do.

**Comment by yasker** [comment]
@hackabletype Thanks for the PR. It looks good!

1. Regarding the Algolia search, it was @lucperkins who helped to add it IIRC. I've just tried, it seems the blog wasn't covered by the Algolia search as well (but Google can find it). @caniszczyk do we have an account with Algolia? 
2. Merge into Longhorn master is fine, since v1.1.0 will merge from master as well.
3. Regarding the format, we can use something like this

```
# Title

## Details

## Resolution

## Related information
```

We should able to put the first post there as a draft, then I can add the real content to it.

**Comment by hackabletype** [comment]
https://deploy-preview-198--longhornio.netlify.app/

@yasker I've made the content example change you've suggested. I'm not able to assign or merge, so if you're happy with this PR I think you'll need to do the merge.

I think if the Algolia also affects the Blog pages, then maybe we should take the Algolia section of [your comment](https://github.com/longhorn/website/pull/198#issuecomment-701710159) and make it a separate issue.

**Comment by yasker** [comment]
@hackabletype Sounds good. I will merge the PR then. Thanks!

**Pull request merged**
