### PR TITLE
Update customizing-default-settings.md

### PR DESCRIPTION
**Pull request by allout58**
Fix formatting so the Markdown renders correctly

### CODE REVIEW

**Comment by catherineluse** [comment]
Can you please sign off on your commit? here's the instructions for how to do it:

> 
> You only have one commit incorrectly signed off! To fix, head to your local branch and run:
> 
> `git commit --amend --signoff`
> 
> Now your commits will have your sign off. Next run
> 
> `git push --force-with-lease origin patch-1`

**Comment by allout58** [comment]
For future reference, do you know if it is possible to do this through the GitHub web interface? I'm assuming I can't amend the commit through it, but it would be nice to do when editing directly from the web the first time.

**Comment by catherineluse** [comment]
Yeah, I have done it through the GitHub UI. Basically, I enter the commit message, then in the larger field below it, I put this text:

> Signed-off-by: Catherine Luse <catherine.luse@gmail.com>

And that seems to satisfy the ci/cd requirement.

**Comment by catherineluse** [comment]
LGTM

**Pull request merged**
