### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by cameronbraid**
added step to create longhorn-system namespace
update helm command use helm v3 syntax (--name not supported)
fix git checkout line as there is no need to cd into longhorn

### CODE REVIEW

**Comment by yasker** [comment]
Thanks @cameronbraid , though we already have another PR for helm3 at https://github.com/longhorn/longhorn/pull/1080 . We will update the doc site once it's updated in the longhorn/longhorn repo.

And eventually we will move all the docs to this repo from longhorn/longhorn.

**Comment by catherineluse** [comment]
This change already exists in the staging branch. It would be nice to have it in master, but it will need to be rebased first.

**Comment by catherineluse** [comment]
I think this PR should be closed in favor of https://github.com/longhorn/website/pull/95

**Comment by yasker** [comment]
Thanks @catherineluse , yeah since #95 covered this, close this one in favor of #95.

**Pull request closed without merging**
