### PR TITLE
docs(detach): Explain how to scale down DaemonSets

### PR DESCRIPTION
**Pull request by hnicke**
#### What this PR does / why we need it:
Explain how to scale down DaemonSets without deleting the DaemonSet.

### CODE REVIEW

**Review by jhkrug — APPROVED** [review]
lgtm

**Comment by derekbit** [comment]
LGTM. Any concern @PhanLe1010 @c3y1huang @shuo-wu @innobead?

**Review by c3y1huang — CHANGES_REQUESTED** [review]
LGTM, should also include this in 1.6.4 and 1.7.2 docs.

**Comment by derekbit** [comment]
@hnicke Thanks for the contribution. Can you apply the updates to v1.6.4 and v1.7.2 as well? Thanks.

**Review by derekbit — APPROVED** [review]

**Pull request merged**
