### PR TITLE
fix: fixed YAML structure

### PR DESCRIPTION
**Pull request by trayla**
The YAML indentation was wrong and should be valid now.

### CODE REVIEW

**Comment by yasker** [comment]
Thank you @trayla for the PR. Can you sign off the commit (https://github.com/longhorn/website#sign-off-on-all-commits) so we can merge it?

**Comment by trayla** [comment]
Hopefully I did it right now.

**Comment by yasker** [comment]
It seems the `Author` and `Signed-off-by` are mismatched so DCO bot complains. https://github.com/longhorn/website/pull/248/checks?check_run_id=1645348995

**Comment by trayla** [comment]
Sorry, I didn’t know this feature until know. I changed the Email address again.

**Review by yasker — APPROVED** [review]

**Comment by yasker** [comment]
Merged, thanks @trayla !

**Pull request merged**
