### PR TITLE
doc(scheduling): add allow empty selector settings

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: [longhorn/longhorn#4826](https://github.com/longhorn/longhorn/issues/4826)

### CODE REVIEW

**Review by derekbit — DISMISSED** [review]

**Comment by james-munson** [comment]
This is only a global setting, not a storage class or volume parameter?

**Comment by ChanYiLin** [comment]
Hi @james-munson
Yes, it is a global setting

The use case is for example:
User has a set of hosts with SSD and have the tag: ["SSD"]
But user just want Volumes with selector: ["SSD"] to be scheduled on those hosts.
Without this setting, user needs to add selectors for all other Volumes with different selectors or Volumes with empty selector will still have chance to be placed on those hosts. This is inefficient.

We don't need this setting to be Volume level because it can be achieved by using selectors/tags already
Lets say
For a `nodeA:[“ssd”]`
You want `VolumeA:[]`  to be able to be scheduled on it and `VolumeB:[]` cant be scheduled on it
You can just give `VolumeA: ["SSD"]` label to achieve it.

**Review by ejweber — APPROVED** [review]

**Comment by roger-ryao** [comment]
Hi @ChanYiLin 
   https://github.com/longhorn/longhorn/issues/4826  is set for milestone `v1.6.0`. I believe that https://github.com/longhorn/website/pull/770 should be placed in `/content/docs/1.6.0` instead of `/content/docs/1.5.1`, is that correct?

**Comment by ChanYiLin** [comment]
> Hi @ChanYiLin [longhorn/longhorn#4826](https://github.com/longhorn/longhorn/issues/4826) is set for milestone `v1.6.0`. I believe that #770 should be placed in `/content/docs/1.6.0` instead of `/content/docs/1.5.1`, is that correct?

Yes, you are right, thanks!

**Review by roger-ryao — CHANGES_REQUESTED** [review]
It should be placed in `/content/docs/1.6.0` instead of `/content/docs/1.5.1`

**Comment by ChanYiLin** [comment]
@roger-ryao fixed, thanks!

**Review by innobead — APPROVED** [review]

**Pull request merged**
