### PR TITLE
docs: added how to create PV from encrypted volume step

### PR DESCRIPTION
**Pull request by BhautikChudasama**
#### Which issue(s) this PR fixes:
Issue https://github.com/longhorn/longhorn/issues/9571

### CODE REVIEW

**Comment by c3y1huang** [comment]
@BhautikChudasama , thank you for your contribution! Could you also help to apply the changes to versions `1.6.4`, `1.7.2`, and `1.8.0`?

**Comment by BhautikChudasama** [comment]
@c3y1huang updated, thanks.

**Comment by c3y1huang** [comment]
LGTM cc @derekbit

**Review by derekbit — APPROVED** [review]

**Comment by derekbit** [comment]
@BhautikChudasama Thanks for the contribution.

**Comment by innobead** [comment]
cc @longhorn/doc

**Pull request merged**
