### PR TITLE
Add settings for custom mkfs.ext4 parameters

### PR DESCRIPTION
**Pull request by joshimoo**
longhorn/longhorn#1208

Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

### CODE REVIEW

**Comment by yasker** [comment]
LGTM.

**Comment by joshimoo** [comment]
@catherineluse any changes required?

**Comment by yasker** [comment]
Ping @catherineluse ?

**Comment by yasker** [comment]
Seems now covered by https://github.com/longhorn/website/pull/121

**Comment by joshimoo** [comment]
The process is a little weird, with the way we are going to merge these commits. But I am okay with the changes :)

@catherineluse @yasker please feel free to close this pr then once the other issue is merged

**Pull request closed without merging**
