### PR TITLE
Docs to website migration

### PR DESCRIPTION
**Pull request by JasonvanBrackel**
Move and merge documentation from longhorn/longhorn to longhron/website

### CODE REVIEW

**Comment by yasker** [comment]
Hi Jason,

Can you squash the commits into one? We cannot have the merge commits in the PR.

**Comment by JasonvanBrackel** [comment]
Sure thing!

 Will take care of it shortly

JvB

Jason L. van Brackel
jason@vanbrackel.net

**Comment by JasonvanBrackel** [comment]
I'll have the PR today.  I did something evil to the commit history and can't seem to rebase it.  Going to start at master and cherry-pick the changes

**Comment by JasonvanBrackel** [comment]
Going to replace the PR

**Pull request closed without merging**
