### PR TITLE
Update docs to reference longhorn namespace for installation daemonsets

### PR DESCRIPTION
**Pull request by samtudor0112**
#### Which issue(s) this PR fixes:
Issue https://github.com/longhorn/longhorn/issues/8855

#### What this PR does / why we need it:
Old exemplar commands won't work once namespace is changed

#### Additional documentation or context
https://github.com/longhorn/longhorn/pull/8856

### CODE REVIEW

**Comment by jillian-maroket** [comment]
@derekbit Please check the suggested change. Thanks!

**Comment by samtudor0112** [comment]
The code change associated with this PR has now been merged. This PR now needs to be merged before the 1.6.3 release otherwise the docs will be incorrect. Please review and approve. Thanks!

**Comment by derekbit** [comment]
Hello @samtudor0112 
Let's put the change in v1.8.0. I will merge it after releasing v1.7.0 GA. Thank you.

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
