### PR TITLE
doc(recurring-job): new task types

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/3836

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM. Thanks, Chinya.

Can merge this when implementation PRs get merged.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x v1.3.x

**Comment by innobead** [comment]
@c3y1huang I missed this also required for 1.4.1 and 1.3.3. Please help update them as well.

**Comment by c3y1huang** [comment]
> @c3y1huang I missed this also required for 1.4.1 and 1.3.3. Please help update them as well.

https://github.com/longhorn/website/pull/666

**Pull request merged**
