### PR TITLE
docs(1.7.1): update important-notes

### PR DESCRIPTION
**Pull request by derekbit**
Add "Add "Volume Locality for RWX Volumes"

#### Which issue(s) this PR fixes:

Issue #

### CODE REVIEW

**Review by innobead — DISMISSED** [review]
The statement is captured from the original page which has been reviewed, so doc review can be skipped.​​​​​​​​​​​​​​​​

**Comment by innobead** [comment]
@derekbit Have we figured out the failed PR checks?

**Comment by derekbit** [comment]
> @derekbit Have we figured out the failed PR checks?

Fixed the link error. Thank you.

**Comment by derekbit** [comment]
BTW, I removed the last replica handling from my PR. @ejweber has added it in https://github.com/longhorn/website/pull/980.

**Comment by innobead** [comment]
@derekbit lets update the description of this PR, since it still mentioned last replica.

**Comment by derekbit** [comment]
> @derekbit lets update the description of this PR, since it still mentioned last replica.

Updated. Thanks.

**Review by innobead — APPROVED** [review]

**Pull request merged**
