### PR TITLE
Add Documentation for the new Volume Attachment Recovery Policy

### PR DESCRIPTION
**Pull request by joshimoo**
Draft for the Volume Attachment recovery behavior.

longhorn/longhorn#820

### CODE REVIEW

**Comment by yasker** [comment]
`recovery policy`

**Comment by yasker** [comment]
@joshimoo Is this PR ready for review or merge?

**Comment by joshimoo** [comment]
@yasker not yet, will update tonight. Then it should be ready for review.

**Comment by joshimoo** [comment]
@yasker ready for review, I added a summary to the settings page that links to the details on the node failure page.

**Comment by yasker** [comment]
Content LGTM.

**Comment by catherineluse** [comment]
This PR edited settings.md. To make it easier to merge this change into staging, I'm going to remove the edits to settings.md from this PR, and add them to this commit instead. https://github.com/longhorn/website/pull/121/commits/08b737647c54d0cb0de3c07947fc3c32280e0ba3

**Comment by joshimoo** [comment]
@catherineluse the index has not been updated to point to the new settings.
The build failure is related to that update.
Let me know once that is fixed and I will rebase this commit again.

**Comment by catherineluse** [comment]
I don't know how to update the index, what do you mean?

**Comment by joshimoo** [comment]
@catherineluse 
I am referring to the build failure below, the failure is a result of the settings.md changes that got merged. What I am saying is that the current staging branch is broken.

Please see below:
```
9:23:50 PM: docs/0.8.1/deploy/upgrade/longhorn-manager/index.html
9:23:50 PM:   hash does not exist --- docs/0.8.1/deploy/upgrade/longhorn-manager/index.html --> ../../../references/settings/#replica-soft-anti-affinity
```

**Comment by catherineluse** [comment]
To me, that error message is just saying that `../../../references/settings/#replica-soft-anti-affinity` is a broken link.

I think it will work if line 40 of longhorn-manager.md is changed to 

`1. We also recommend updating the **Replica Node Soft Anti-affinity** setting to false. Refer to the [settings reference](../../../references/settings/#replica-node-level-soft-anti-affinity) for details.`

**Pull request merged**
