### PR TITLE
Apply editorial updates from Alex's old PR

### PR DESCRIPTION
**Pull request by jillian-maroket**
#### Which issue(s) this PR fixes:
See [PR 856](https://github.com/longhorn/website/pull/856/).

#### What this PR does / why we need it:
Changes from PR 856 must be applied to all other active versions.

### CODE REVIEW

**Review by derekbit — APPROVED** [review]

**Comment by derekbit** [comment]
@jillian-maroket need to resolve conflicts before merging it, thanks.

**Comment by jillian-maroket** [comment]
@derekbit I don't know why those commits are included in this PR and why the codespell issues exist. The problematic commits are from [PR 914](https://github.com/longhorn/website/pull/914) and the codespell issues were fixed in [PR 912](https://github.com/longhorn/website/pull/912).

How should I proceed?

**Review by derekbit — DISMISSED** [review]

**Comment by derekbit** [comment]
> @derekbit I don't know why those commits are included in this PR and why the codespell issues exist. The problematic commits are from [PR 914](https://github.com/longhorn/website/pull/914) and the codespell issues were fixed in [PR 912](https://github.com/longhorn/website/pull/912).
> 
> How should I proceed?

No worries. I helped rebase your PR.
Remember to pull rebase it to prevent conflicts next time. Thank you.

**Comment by derekbit** [comment]
@jillian-maroket The commit is not signed. Please help sign it. Thank you.

**Comment by jillian-maroket** [comment]
I just manually approved the commit sign-off again. As mentioned in our chat, I did that after creating the PR but it disappeared. 

Anyway, thanks for helping rebase the PR. I made sure to pull before creating the branch to avoid conflicts but somehow unrelated commits still appeared. I'll try rebasing and force-pushing next time.

**Review by derekbit — APPROVED** [review]

**Pull request merged**
